In [1]:
import numpy as np

# Replace None with appropriate code
X = np.arange(2,34,2)
X = np.reshape(X, (4,4))
print(X)



[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


**method 2**

In [2]:
import numpy as np

# Replace None with appropriate code
X = np.linspace(2,32,16).reshape(4,4)
print(X)



[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]
